-- 회원 관리
CREATE TABLE MEMBER_INFO
(
    MEMBER_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(45) UNIQUE NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    DONG VARCHAR(45) NOT NULL,
    HO VARCHAR(45) NOT NULL,
    PHONE_NUM VARCHAR(45) NOT NULL,
    TYPE VARCHAR(45) NOT NULL,
    REMARK VARCHAR(45)
);

-- 단발성 방문자
CREATE TABLE GUEST
(
    GUEST_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(45) UNIQUE NOT NULL, 
    VISIT_DATE DATE,
    DONG VARCHAR(45),
    HO VARCHAR(45),
    PHONE_NUM VARCHAR(45),
    NAME VARCHAR(45) NOT NULL,
    REMARK VARCHAR(45),
    TYPE VARCHAR(45) NOT NULL,

    FOREIGN KEY(CAR_NUM) REFERENCES MEMBER_INFO(CAR_NUM)
);

-- 정기 방문자
CREATE TABLE BOOKED
(
    BOOKED_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(45) UNIQUE NOT NULL,
    BOOKED_PURPOSE VARCHAR(45) NOT NULL,
    VALIDITY DATE NOT NULL,
    PHONE_NUM VARCHAR(45) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    COMPANY_NAME VARCHAR(45),
    REMARK VARCHAR(45),
    TYPE VARCHAR(45) NOT NULL,

    FOREIGN KEY(CAR_NUM) REFERENCES MEMBER_INFO(CAR_NUM)
);

-- 계정정보
CREATE TABLE USER_INFO
(
    USER_NUM INT PRIMARY KEY,
    USER_ID VARCHAR(45) UNIQUE NOT NULL,
    USER_ROLE VARCHAR(45) NOT NULL
);

-- 상점
CREATE TABLE STORE
(
    STORE_NUM INT PRIMARY KEY,
    STORE_NAME VARCHAR(45) UNIQUE NOT NULL,
    PHONE_NUM VARCHAR(45) NOT NULL,
    ADDR VARCHAR(45) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    JOINED_DATE DATE NOT NULL,
    REMARK VARCHAR(45)  
);