SELECT * FROM BOOKED

DROP TABLE IF EXISTS BOOKED;
DROP TABLE IF EXISTS STORE_PAYMENT_INFO;
DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS ACCOUNT_INFO;
DROP TABLE IF EXISTS CAR_INFO;
DROP TABLE IF EXISTS GUEST;
DROP TABLE IF EXISTS MEMBER_INFO;
DROP TABLE IF EXISTS MEMBER_TYPE;