CREATE TABLE IF NOT EXISTS MEMBER_INFO
(
    MEMBER_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(8) UNIQUE NOT NULL,
    NAME VARCHAR(5) NOT NULL,
    DONG INT NOT NULL,
    HO INT NOT NULL,
    PHONE_NUM VARCHAR(13) NOT NULL,
    TYPE VARCHAR(3) NOT NULL,
    REMARK VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS GUEST
(
    GUEST_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(8) UNIQUE NOT NULL,
    NAME VARCHAR(5) NOT NULL,
    DONG INT,
    HO INT,
    PHONE_NUM VARCHAR(13),
    TYPE VARCHAR(3) NOT NULL,
    VISIT_DATE DATE,
    REMARK VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS BOOKED
(
    BOOKED_NUM INT PRIMARY KEY,
    CAR_NUM VARCHAR(8) UNIQUE NOT NULL,
    BOOKED_PURPOSE VARCHAR(10) NOT NULL,
    VALIDITY DATE NOT NULL,
    PHONE_NUM VARCHAR(13) NOT NULL,
    NAME VARCHAR(5) NOT NULL,
    COMPANY_NAME VARCHAR(10),
    REMARK VARCHAR(20),
    TYPE VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_INFO
(
    USER_NUM INT PRIMARY KEY,
    USER_ID VARCHAR(15) UNIQUE NOT NULL,
    USER_PW VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS STORE
(
    STORE_NUM INT PRIMARY KEY,
    STORE_NAME VARCHAR(10) UNIQUE NOT NULL,
    PHONE_NUM VARCHAR(13) NOT NULL,
    ADDR VARCHAR(30) NOT NULL,
    OWNER_NAME VARCHAR(5) NOT NULL,
    JOINED_DATE DATE NOT NULL,
    REMARK VARCHAR(20)  
);